# Generated by Django 3.2.25 on 2024-05-22 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='traffic_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('serial_number', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('line', models.CharField(max_length=100)),
                ('judgement', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
